application:
  tickets:
    Adult:
      minAge: 18
      maxAge: 64
      price: 25
    Senior:
      minAge: 65
      baseGroup: Adult
      adjustPercent: -30
    Teen:
      minAge: 11
      maxAge: 17
      price: 12
    Children:
      maxAge: 10
      price: 5
  discounts:
    Children:
      adjustPercent: -25
      minTickets: 3

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus,health,env,metrics,configprops,mappings
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            request: true

logging:
  pattern:
    level: "%5p [correlationId=%X{correlationId:-},traceId=%X{traceId:-},spanId=%X{spanId:-}]"
  level:
    per.duyd: DEBUG